# Models
from api_flask.apps.Attack.models import Country
# Api url
from api_flask.config import elk_url,headers
import requests
import simplejson as json
import datetime
# tiempo 
lte = datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%SZ")
gte = (datetime.datetime.now()-datetime.timedelta(days=1)).strftime("%Y-%m-%dT%H:%M:%SZ")
def getDataElk():
    query = json.dumps(
        {
            "aggs": {
                "2": {
                    "terms": {
                        "field": "city_code.keyword",
                        "order": {"_count": "desc"},
                        "size": 300,
                    }
                }
            },
            "size": 0,
            "_source": {"excludes": []},
            "stored_fields": ["*"],
            "script_fields": {},
            "docvalue_fields": [{"field": "timestamp", "format": "date_time"}],
            "query": {
                "bool": {
                    "must": [
                        {"exists": {"field": "incapsula_attack"}},
                        {"exists": {"field": "city_code"}},
                        {
                            "range": {
                                "timestamp": {
                                    "format": "strict_date_optional_time",
                                    "gte": gte,
                                    "lte": lte,
                                }
                            }
                        },
                    ],
                    "filter": [{"match_all": {}}, {"match_all": {}}],
                    "should": [],
                    "must_not": [
                        {"match_phrase": {"incapsula_attack": {"query": "n/a"}}}
                    ],
                }
            },
        }
    )
    try:
        r = requests.post(elk_url, data=query, headers=headers)
        results = json.loads(r.text)
        return  results["aggregations"]["2"]["buckets"]
    except requests.exceptions.ConnectionError as e:
        print(e)


iso_names = {
    "n/a": "El-mar",
    "AF": "afghanistan",
    "AX": "åland-islands",
    "AL": "albania",
    "DZ": "algeria",
    "AS": "american-samoa",
    "AD": "andorra",
    "AO": "angola",
    "AI": "anguilla",
    "AQ": "antarctica",
    "AG": "antigua-and-barbuda",
    "AR": "argentina",
    "AM": "armenia",
    "AW": "aruba",
    "AU": "australia",
    "AT": "austria",
    "AZ": "azerbaijan",
    "BS": "bahamas",
    "BH": "bahrain",
    "BD": "bangladesh",
    "BB": "barbados",
    "BY": "belarus",
    "BE": "belgium",
    "BZ": "belize",
    "BJ": "benin",
    "BM": "bermuda",
    "BT": "bhutan",
    "BO": "bolivia-(plurinational-state-of)",
    "BQ": "bonaire,-sint-eustatius-and-saba",
    "BA": "bosnia-and-herzegovina",
    "BW": "botswana",
    "BV": "bouvet-island",
    "BR": "brazil",
    "IO": "british-indian-ocean-territory",
    "BN": "brunei-darussalam",
    "BG": "bulgaria",
    "BF": "burkina-faso",
    "BI": "burundi",
    "CV": "cabo-verde",
    "KH": "cambodia",
    "CM": "cameroon",
    "CA": "canada",
    "KY": "cayman-islands",
    "CF": "central-african-republic",
    "TD": "chad",
    "CL": "chile",
    "CN": "china",
    "CX": "christmas-island",
    "CC": "cocos-(keeling)-islands",
    "CO": "colombia",
    "KM": "comoros",
    "CG": "congo",
    "CD": "congo,-democratic-republic-of-the",
    "CK": "cook-islands",
    "CR": "costa-rica",
    "CI": "côte-d'ivoire",
    "HR": "croatia",
    "CU": "cuba",
    "CW": "curaçao",
    "CY": "cyprus",
    "CZ": "czechia",
    "DK": "denmark",
    "DJ": "djibouti",
    "DM": "dominica",
    "DO": "dominican-republic",
    "EC": "ecuador",
    "EG": "egypt",
    "SV": "el-salvador",
    "GQ": "equatorial-guinea",
    "ER": "eritrea",
    "EE": "estonia",
    "SZ": "eswatini",
    "ET": "ethiopia",
    "FK": "falkland-islands-(malvinas)",
    "FO": "faroe-islands",
    "FJ": "fiji",
    "FI": "finland",
    "FR": "france",
    "GF": "french-guiana",
    "PF": "french-polynesia",
    "TF": "french-southern-territories",
    "GA": "gabon",
    "GM": "gambia",
    "GE": "georgia",
    "DE": "germany",
    "GH": "ghana",
    "GI": "gibraltar",
    "GR": "greece",
    "GL": "greenland",
    "GD": "grenada",
    "GP": "guadeloupe",
    "GU": "guam",
    "GT": "guatemala",
    "GG": "guernsey",
    "GN": "guinea",
    "GW": "guinea-bissau",
    "GY": "guyana",
    "HT": "haiti",
    "HM": "heard-island-and-mcdonald-islands",
    "VA": "holy-see",
    "HN": "honduras",
    "HK": "hong-kong",
    "HU": "hungary",
    "IS": "iceland",
    "IN": "india",
    "ID": "indonesia",
    "IR": "iran-(islamic-republic-of)",
    "IQ": "iraq",
    "IE": "ireland",
    "IM": "isle-of-man",
    "IL": "israel",
    "IT": "italy",
    "JM": "jamaica",
    "JP": "japan",
    "JE": "jersey",
    "JO": "jordan",
    "KZ": "kazakhstan",
    "KE": "kenya",
    "KI": "kiribati",
    "KP": "korea-(democratic-people's-republic-of)",
    "KR": "korea,-republic-of",
    "KW": "kuwait",
    "KG": "kyrgyzstan",
    "LA": "lao-people's-democratic-republic",
    "LV": "latvia",
    "LB": "lebanon",
    "LS": "lesotho",
    "LR": "liberia",
    "LY": "libya",
    "LI": "liechtenstein",
    "LT": "lithuania",
    "LU": "luxembourg",
    "MO": "macao",
    "MG": "madagascar",
    "MW": "malawi",
    "MY": "malaysia",
    "MV": "maldives",
    "ML": "mali",
    "MT": "malta",
    "MH": "marshall-islands",
    "MQ": "martinique",
    "MR": "mauritania",
    "MU": "mauritius",
    "YT": "mayotte",
    "MX": "mexico",
    "FM": "micronesia-(federated-states-of)",
    "MD": "moldova,-republic-of",
    "MC": "monaco",
    "MN": "mongolia",
    "ME": "montenegro",
    "MS": "montserrat",
    "MA": "morocco",
    "MZ": "mozambique",
    "MM": "myanmar",
    "NA": "namibia",
    "NR": "nauru",
    "NP": "nepal",
    "NL": "netherlands",
    "NC": "new-caledonia",
    "NZ": "new-zealand",
    "NI": "nicaragua",
    "NE": "niger",
    "NG": "nigeria",
    "NU": "niue",
    "NF": "norfolk-island",
    "MK": "north-macedonia",
    "MP": "northern-mariana-islands",
    "NO": "norway",
    "OM": "oman",
    "PK": "pakistan",
    "PW": "palau",
    "PS": "palestine,-state-of",
    "PA": "panama",
    "PG": "papua-new-guinea",
    "PY": "paraguay",
    "PE": "peru",
    "PH": "philippines",
    "PN": "pitcairn",
    "PL": "poland",
    "PT": "portugal",
    "PR": "puerto-rico",
    "QA": "qatar",
    "RE": "réunion",
    "RO": "romania",
    "RU": "russia",
    "RW": "rwanda",
    "BL": "saint-barthélemy",
    "SH": "saint-helena,-ascension-and-tristan-da-cunha",
    "KN": "saint-kitts-and-nevis",
    "LC": "saint-lucia",
    "MF": "saint-martin-(french-part)",
    "PM": "saint-pierre-and-miquelon",
    "VC": "saint-vincent-and-the-grenadines",
    "WS": "samoa",
    "SM": "san-marino",
    "ST": "sao-tome-and-principe",
    "SA": "saudi-arabia",
    "SN": "senegal",
    "RS": "serbia",
    "SC": "seychelles",
    "SL": "sierra-leone",
    "SG": "singapore",
    "SX": "sint-maarten-(dutch-part)",
    "SK": "slovakia",
    "SI": "slovenia",
    "SB": "solomon-islands",
    "SO": "somalia",
    "ZA": "south-africa",
    "GS": "south-georgia-and-the-south-sandwich-islands",
    "SS": "south-sudan",
    "ES": "spain",
    "LK": "sri-lanka",
    "SD": "sudan",
    "SR": "suriname",
    "SJ": "svalbard-and-jan-mayen",
    "SE": "sweden",
    "CH": "switzerland",
    "SY": "syrian-arab-republic",
    "TW": "taiwan,-province-of-china",
    "TJ": "tajikistan",
    "TZ": "tanzania,-united-republic-of",
    "TH": "thailand",
    "TL": "timor-leste",
    "TG": "togo",
    "TK": "tokelau",
    "TO": "tonga",
    "TT": "trinidad-and-tobago",
    "TN": "tunisia",
    "TR": "turkey",
    "TM": "turkmenistan",
    "TC": "turks-and-caicos-islands",
    "TV": "tuvalu",
    "UG": "uganda",
    "UA": "ukraine",
    "AE": "united-arab-emirates",
    "GB": "ireland",
    "US": "united-states-of-america",
    "UM": "united-states-minor-outlying-islands",
    "UY": "uruguay",
    "UZ": "uzbekistan",
    "VU": "vanuatu",
    "VE": "venezuela-(bolivarian-republic-of)",
    "VN": "viet-nam",
    "VG": "virgin-islands-(british)",
    "VI": "virgin-islands-(u.s.)",
    "WF": "wallis-and-futuna",
    "EH": "western-sahara",
    "YE": "yemen",
    "ZM": "zambia",
    "ZW": "zimbabwe",
}


def getData():
    countries = []
    data = getDataElk()
    for c in data:
        color = getColor(c["doc_count"])
        key = c["key"].replace(",", "").split()
        if len(key) != 1:
            for code in key:
                name = iso_names[code]
                code = checkCode(code)
                city = Country(name, c["doc_count"], color, code)
        else:
            code = checkCode(c["key"])
            city = Country(iso_names[c["key"]], c["doc_count"], color, code)
        countries.append(city.__dict__)
    return countries

    # Hoy en dia nos gobierna la estupides, dajaron destruir el sistema de agua el sistema alimenticio,
    # nuestro desafio es contra la estupides.


def getColor(num):
    if num < 10:
        color = "#fe4d97c9"
    elif num < 100:
        color = "#26c1c9c9"
    elif num < 500:
        color = "#1ca9e9c9"
    elif num < 1000:
        color = "#0154c8c9"
    else:
        color = "#6658cbc9"
    return color


def checkCode(code):
    if code == "n/a":
        code = "MAR"
    return code

    # r = {
    #     "took": 3112,
    #     "timed_out": False,
    #     "_shards": {"total": 8, "successful": 8, "skipped": 0, "failed": 0},
    #     "hits": {"total": 4935608, "max_score": None, "hits": []},
    #     "aggregations": {
    #         "2": {
    #             "doc_count_error_upper_bound": 0,
    #             "sum_other_doc_count": 0,
    #             "buckets": [
    #                 {"key": "n/a", "doc_count": 4639476},
    #                 {"key": "CL", "doc_count": 7},
    #                 {"key": "US", "doc_count": 194930},
    #                 {"key": "BR", "doc_count": 23340},
    #                 {"key": "ES", "doc_count": 9667},
    #                 {"key": "DE", "doc_count": 7992},
    #                 {"key": "AR", "doc_count": 6498},
    #                 {"key": "MX", "doc_count": 4843},
    #                 {"key": "FR", "doc_count": 4516},
    #                 {"key": "PE", "doc_count": 3977},
    #                 {"key": "GB", "doc_count": 3662},
    #                 {"key": "IT", "doc_count": 3619},
    #                 {"key": "AU", "doc_count": 3286},
    #                 {"key": "CO", "doc_count": 2891},
    #                 {"key": "CA", "doc_count": 2148},
    #                 {"key": "NL", "doc_count": 1320},
    #                 {"key": "HR", "doc_count": 1282},
    #                 {"key": "CH", "doc_count": 1115},
    #                 {"key": "IN", "doc_count": 940},
    #                 {"key": "NO", "doc_count": 885},
    #                 {"key": "EC", "doc_count": 883},
    #                 {"key": "DK", "doc_count": 832},
    #                 {"key": "CZ", "doc_count": 830},
    #                 {"key": "SE", "doc_count": 760},
    #                 {"key": "UY", "doc_count": 612},
    #                 {"key": "IL", "doc_count": 585},
    #                 {"key": "IE", "doc_count": 580},
    #                 {"key": "JP", "doc_count": 575},
    #                 {"key": "DO", "doc_count": 536},
    #                 {"key": "VE", "doc_count": 534},
    #                 {"key": "RU", "doc_count": 512},
    #                 {"key": "TR", "doc_count": 506},
    #                 {"key": "PT", "doc_count": 443},
    #                 {"key": "PA", "doc_count": 407},
    #                 {"key": "PL", "doc_count": 372},
    #                 {"key": "TH", "doc_count": 366},
    #                 {"key": "CR", "doc_count": 337},
    #                 {"key": "BO", "doc_count": 323},
    #                 {"key": "KR", "doc_count": 315},
    #                 {"key": "JM", "doc_count": 311},
    #                 {"key": "NZ", "doc_count": 300},
    #                 {"key": "BE", "doc_count": 294},
    #                 {"key": "RO", "doc_count": 265},
    #                 {"key": "CN", "doc_count": 259},
    #                 {"key": "TW", "doc_count": 251},
    #                 {"key": "PY", "doc_count": 233},
    #                 {"key": "AT", "doc_count": 184},
    #                 {"key": "FI", "doc_count": 165},
    #                 {"key": "UA", "doc_count": 153},
    #                 {"key": "HK", "doc_count": 151},
    #                 {"key": "CY", "doc_count": 150},
    #                 {"key": "AW", "doc_count": 142},
    #                 {"key": "IM", "doc_count": 139},
    #                 {"key": "SI", "doc_count": 133},
    #                 {"key": "MA", "doc_count": 119},
    #                 {"key": "GR", "doc_count": 108},
    #                 {"key": "CU", "doc_count": 106},
    #                 {"key": "AZ", "doc_count": 104},
    #                 {"key": "BG", "doc_count": 101},
    #                 {"key": "AE", "doc_count": 99},
    #                 {"key": "BA", "doc_count": 82},
    #                 {"key": "GT", "doc_count": 69},
    #                 {"key": "ZA", "doc_count": 54},
    #                 {"key": "MN", "doc_count": 53},
    #                 {"key": "HU", "doc_count": 51},
    #                 {"key": "PH", "doc_count": 51},
    #                 {"key": "LK", "doc_count": 50},
    #                 {"key": "PR", "doc_count": 48},
    #                 {"key": "HN", "doc_count": 44},
    #                 {"key": "SA", "doc_count": 43},
    #                 {"key": "EE", "doc_count": 35},
    #                 {"key": "LA", "doc_count": 35},
    #                 {"key": "QA", "doc_count": 23},
    #                 {"key": "SK", "doc_count": 23},
    #                 {"key": "BS", "doc_count": 14},
    #                 {"key": "CL, BR", "doc_count": 13},
    #                 {"key": "MZ", "doc_count": 12},
    #                 {"key": "SG", "doc_count": 10},
    #                 {"key": "SV", "doc_count": 9},
    #                 {"key": "GH", "doc_count": 8},
    #                 {"key": "TN", "doc_count": 8},
    #                 {"key": "BD", "doc_count": 4},
    #                 {"key": "ME", "doc_count": 4},
    #                 {"key": "KZ", "doc_count": 3},
    #                 {"key": "RS", "doc_count": 3},
    #                 {"key": "CW", "doc_count": 2},
    #                 {"key": "ID", "doc_count": 2},
    #                 {"key": "KW", "doc_count": 2},
    #                 {"key": "AL", "doc_count": 1},
    #                 {"key": "EG", "doc_count": 1},
    #                 {"key": "IR", "doc_count": 1},
    #                 {"key": "NP", "doc_count": 1},
    #                 {"key": "PK", "doc_count": 1},
    #             ],
    #         }
    #     },
    #     "status": 200,
    # }
